version: "3.9"
services:
  db:
    image: postgres:15.1
    volumes:
      - "postgres:/data/postgres"
    environment:
      POSTGRES_PASSWORD: password
      BUNDLE_FORCE_RUBY_PLATFORM: "true"
      PGDATA: /data/postgres
    ports:
      - "6543:5432"

  server:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/stock-processor
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOSTNAME: db
      DB_USERNAME: postgres
      DB_PASSWORD: password
    tty: true
    stdin_open: true

volumes:
  postgres:
