---
:concurrency: 5
:queues:
  - high_priority
  - default
  - low_priority
:scheduler:
  :schedule:
    currency_rate_fetcher_job:
      enabled: true
      cron: "0 0 * * *"
      queue: high_priority
      class: CurrencyRateFetcherJob
